export const FIFTH_GETDIALOG = 'FIFTH_GETDIALOG';
export const FIFTH_GETCOMMONDIALOG = 'FIFTH_GETCOMMONDIALOG';
export const FIFTH_GETCHOOSEDIALOG = 'FIFTH_GETCHOOSEDIALOG';
export const FIFTH_GETPOINT = 'FIFTH_GETPOINT';