export const FIN_GETDIALOG = 'FIN_GETDIALOG';
export const FIN_GETCOMMONDIALOG = 'FIN_GETCOMMONDIALOG';
export const FIN_GETCHOOSEDIALOG = 'FIN_GETCHOOSEDIALOG';
export const FIN_GETPOINT = 'FIN_GETPOINT';